services:
  mortgage-calc:
    container_name: mortgage-calc
    build: .
    labels:
      # Expose HTTPS endpoint with traefik
      - 'traefik.enable=true'
      - 'traefik.http.routers.mortgage-calc.rule=Host(`mortgage-calc.jamesmassucco.com`)'
      - 'traefik.http.routers.mortgage-calc.entrypoints=websecure'
      - 'traefik.http.routers.mortgage-calc.tls=true'
      - 'traefik.http.routers.mortgage-calc.tls.certresolver=cloudflare'
      - 'traefik.http.services.mortgage-calc.loadbalancer.server.port=8000'
      # Use rate-limiting
      - traefik.http.routers.mortgage-calc.middlewares=ratelimit,oauth-auth
    networks:
      - web
    volumes:
      - data-volume:/data
    restart: unless-stopped

volumes:
  data-volume:

networks:
  web:
    external: true
