services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    command: >
      bash -c "
      ollama pull mistral &&
      ollama serve
      "
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_NUM_THREAD=4  # Control CPU usage
      - OLLAMA_MAX_MODEL_SIZE=8GiB  # Ensure large models can load
    restart: unless-stopped

volumes:
  ollama-data: