name: Start service
description: Creates the docker web network and starts a service using scripts/start_service.sh

inputs:
  service:
    description: Service directory name (e.g. blog, homepage, travel)
    required: true
  build:
    description: Build image from source instead of pulling from registry
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Create docker web network
      shell: bash
      run: docker network create web 2>/dev/null || true

    - name: Start service via start_service.sh
      shell: bash
      run: |
        ARGS=("${{ inputs.service }}")
        if [[ "${{ inputs.build }}" == "true" ]]; then
          ARGS+=("--build")
        fi
        bash "${{ github.workspace }}/scripts/start_service.sh" "${ARGS[@]}"
