name: 'Build and Push Docker Image'
description: 'Extract metadata, build, and push Docker image to GHCR'
inputs:
  image:
    description: 'Image name (e.g., ghcr.io/jmassucco17/homelab/blog)'
    required: true
  context:
    description: 'Build context path'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  cache-scope:
    description: 'Cache scope name'
    required: true

outputs:
  digest:
    description: 'Image digest (sha256:...)'
    value: ${{ steps.build.outputs.digest }}
  changed:
    description: 'Whether the image content changed'
    value: ${{ steps.check-change.outputs.changed }}

runs:
  using: composite
  steps:
    - name: Get current latest digest
      id: current-digest
      shell: bash
      run: |
        IMAGE="${{ inputs.image }}"
        # Get the current digest of the 'latest' tag before building
        CURRENT_DIGEST=$(docker manifest inspect "${IMAGE}:latest" 2>/dev/null | jq -r '.digest' || echo "")
        echo "digest=${CURRENT_DIGEST}" >> "$GITHUB_OUTPUT"
        if [ -n "$CURRENT_DIGEST" ]; then
          echo "Current latest digest: ${CURRENT_DIGEST}"
        else
          echo "No existing latest tag found"
        fi

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image }}
        tags: |
          type=sha,format=short
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push
      id: build
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha,scope=${{ inputs.cache-scope }}
        cache-to: type=gha,mode=max,scope=${{ inputs.cache-scope }}

    - name: Check if image changed
      id: check-change
      shell: bash
      run: |
        # Get the newly built digest
        NEW_DIGEST="${{ steps.build.outputs.digest }}"
        CURRENT_DIGEST="${{ steps.current-digest.outputs.digest }}"

        echo "Previous digest: ${CURRENT_DIGEST:-none}"
        echo "New digest: ${NEW_DIGEST}"

        if [ -z "$CURRENT_DIGEST" ] || [ "$NEW_DIGEST" != "$CURRENT_DIGEST" ]; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
          echo "Result: Image changed or is new"
        else
          echo "changed=false" >> "$GITHUB_OUTPUT"
          echo "Result: Image unchanged"
        fi
