name: Setup Python
description: Sets up Python 3.12 and installs dependencies via uv sync

runs:
  using: composite
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: '3.12'
        activate-environment: true

    - name: Install dependencies
      shell: bash
      run: uv sync --frozen
