name: Setup Python
description: Sets up Python 3.12 and installs dependencies from requirements.txt

runs:
  using: composite
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: '3.12'

    - name: Install dependencies
      shell: bash
      run: uv pip install --system -r requirements.txt
