name: Set image tag
description: >
  Computes the Docker image tag based on the current commit SHA.
  Requires the repository to be checked out before calling this action.

outputs:
  tag:
    description: 'Docker image tag to use'
    value: ${{ steps.compute.outputs.tag }}

runs:
  using: composite
  steps:
    - name: Compute tag
      id: compute
      shell: bash
      run: echo "tag=sha-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
